### ISSUE TITLE
Fix basic button font-weight

### ISSUE THREAD

**Issue by mairatma** [inloco/supernova-inloco#46]
This is very small, but I'm creating the issue before I forget about it.

@bruno-perruci told me that we're using a wrong font-weight for the basic button:

<img width="747" alt="screen shot 2018-11-07 at 8 25 21 am" src="https://user-images.githubusercontent.com/5216049/48128906-b2da6980-e266-11e8-80a3-448635174dee.png">

**Comment by TCezarRod** [comment]
This bug was already resolved on 0309569534103531480fb5aec73be21f07e0411f
